name: Lint CI

on:
  pull_request:
    branches: ["master"]

jobs:
  run-lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.9
      - name: Set up pip cache
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.cache/pip
            ${{ github.workspace }}/.mypy_cache
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Hatch
        run: pipx install hatch

      - name: Check style and typing
        run: hatch run lint:all
