name: Tests CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run NSIQCppStyle tests
        timeout-minutes: 5
        run: PYTHONPATH=./:./rules python -m unittest discover -s nsiqunittest -p "*.py"

      - name: Run NSIQCppStyle RULES tests
        timeout-minutes: 5
        run: PYTHONPATH=./:./rules python -m unittest discover -s rules -p "*.py"
